# Autogenerated wrapper script for SSW_jll for aarch64-linux-musl-cxx03
export example_c, example_cpp, libssw, ssw_test

using Zlib_jll
JLLWrappers.@generate_wrapper_header("SSW")
JLLWrappers.@declare_library_product(libssw, "libssw.so")
JLLWrappers.@declare_executable_product(example_c)
JLLWrappers.@declare_executable_product(example_cpp)
JLLWrappers.@declare_executable_product(ssw_test)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libssw,
        "lib/libssw.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        example_c,
        "bin/example_c",
    )

    JLLWrappers.@init_executable_product(
        example_cpp,
        "bin/example_cpp",
    )

    JLLWrappers.@init_executable_product(
        ssw_test,
        "bin/ssw_test",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
